//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custumer
    {
        public int IdCustumer { get; set; }
        public string FullNameCustumer { get; set; }
        public string DateOfBirth { get; set; }
        public string Sex { get; set; }
        public int IdTour { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
