//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.Custumers = new HashSet<Custumer>();
            this.DetailTours = new HashSet<DetailTour>();
        }
    
        public int IdTour { get; set; }
        public string TitleTour { get; set; }
        public string DescTour { get; set; }
        public string ImageTour { get; set; }
        public string StartingGate { get; set; }
        public Nullable<System.DateTime> StartTour { get; set; }
        public Nullable<int> TimeTour { get; set; }
        public string Hotel { get; set; }
        public string Vehicle { get; set; }
        public Nullable<int> LuotView { get; set; }
        public Nullable<decimal> PriceTour { get; set; }
        public string Visit { get; set; }
        public string Food { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Custumer> Custumers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailTour> DetailTours { get; set; }
    }
}
